export enum AssetSymbol {
  usdt = 'USDT',
  usd = 'USD',
  btc = 'BTC',
  eth = 'ETH',
  bnb = 'BNB',
  xrp = 'XRP',
  ada = 'ADA',
  doge = 'DOGE',
  matic = 'MATIC',
  shib = 'SHIB',
  dot = 'DOT',
  ltc = 'LTC',
  avax = 'AVAX',
  sol = 'SOL',
  qnt = 'QNT',
  ar = 'AR',
}
